#!/usr/bin/env python3
"""
Generate a narrow Vuo proof composition from a My World clocked graph fixture.

This is intentionally small: it proves that graph metadata can auto-wire
my_MainClock into frame-cooked ports instead of hand-authoring renderTick cables.
"""

from __future__ import annotations

import argparse
import json
from pathlib import Path


CLOCKED_PORTS_BY_TYPE = {
    "my.image.generate.basic.constantImage": ["renderTick"],
    "my.image.use.blend": ["renderTick"],
    "my.image.use.keepPreviousFrame": ["update"],
    "my.image.generate.basic.renderTarget": ["renderTick"],
    "my.render.dx11.api.clearRenderTarget": ["renderTick"],
    "vuo.image.render.window2": ["refresh"],
}


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument("fixture")
    parser.add_argument("--output", required=True)
    args = parser.parse_args()

    fixture_path = Path(args.fixture)
    output_path = Path(args.output)
    fixture = json.loads(fixture_path.read_text(encoding="utf8"))
    clocked_ports = resolve_clocked_ports(fixture)
    composition = render_composition(fixture, clocked_ports)
    output_path.parent.mkdir(parents=True, exist_ok=True)
    output_path.write_text(composition, encoding="utf8")
    print(json.dumps({
        "ok": True,
        "fixture": str(fixture_path),
        "output": str(output_path),
        "nodeCount": len(fixture["nodes"]) + 3,
        "clockedPortCount": len(clocked_ports),
        "edgeCount": len(fixture["edges"]) + len(clocked_ports) + 1,
        "clockedPortsSource": "fixture" if "clockedPorts" in fixture else "inferredFromNodeTypes",
    }, indent=2))
    return 0


def resolve_clocked_ports(fixture: dict) -> list[dict]:
    if "clockedPorts" in fixture:
        return fixture["clockedPorts"]

    clocked_ports: list[dict] = []
    for node in fixture["nodes"]:
        for port in CLOCKED_PORTS_BY_TYPE.get(node["type"], []):
            clocked_ports.append({"node": node["id"], "port": port})
    return clocked_ports


def render_composition(fixture: dict, clocked_ports: list[dict]) -> str:
    name = fixture["name"]
    clock_note = "The graph fixture owns clockedPorts; the generator owns MainClock edges."
    if "clockedPorts" not in fixture:
        clock_note = "The creator graph owns only semantic edges; the generator infers MainClock edges from node type contracts."
    lines = [
        "/**",
        " * @file",
        " * Generated My World main-clock Vuo proof.",
        " *",
        " * Source fixture:",
        f" * - {fixture['name']}",
        " *",
        " * This file is generated by docs/runtime/scripts/generate_vuo_main_clock_proof.py.",
        f" * {clock_note}",
        " *",
        " * @lastSavedInVuoVersion 2.4.6",
        " * @license This composition may be modified and distributed under the terms of the MIT License.",
        " */",
        "",
        "digraph G",
        "{",
        'FireOnDisplayRefresh [type="vuo.event.fireOnDisplayRefresh" version="1.0.0" label="Host Display Refresh|<requestedFrame>requestedFrame\\r" pos="-560,30" fillcolor="lime" _requestedFrame_eventThrottling="drop"];',
        "",
        'MainClock [type="my.runtime.clock.mainClock" version="1.0.0" label="my_MainClock|<HostTime>HostTime\\l|<clockIn>clockIn\\l|<FrameIndex>FrameIndex\\r|<Time>Time\\r|<DeltaTime>DeltaTime\\r|<renderTick>renderTick\\r" pos="-360,30" fillcolor="#868C8D"];',
        "",
    ]

    for node in fixture["nodes"]:
        lines.append(render_node(node))
        lines.append("")

    lines.append('Comment [type="vuo.comment" label="\\"Generated main-clock proof\\"" pos="420,-245" width="380" height="42"];')
    lines.append("")
    lines.append("FireOnDisplayRefresh:requestedFrame -> MainClock:HostTime;")

    for target in clocked_ports:
        lines.append(f"MainClock:renderTick -> {target['node']}:{target['port']};")

    for edge in fixture["edges"]:
        from_node, from_port = edge["from"]
        to_node, to_port = edge["to"]
        lines.append(f"{from_node}:{from_port} -> {to_node}:{to_port};")

    lines.append("}")
    return "\n".join(lines) + "\n"


def render_node(node: dict) -> str:
    ports = node.get("vuoPorts") or node["ports"]
    label = render_label(node["label"], ports["inputs"], ports["outputs"])
    attrs = [
        f'type="{node["type"]}"',
        f'version="{node.get("version", "1.0.0")}"',
        f'label="{label}"',
        f'pos="{node["pos"][0]},{node["pos"][1]}"',
        f'fillcolor="{node["fillcolor"]}"',
    ]
    for key, value in node.get("attrs", {}).items():
        attrs.append(f'_{key}="{value}"')
    return f"{node['id']} [{ ' '.join(attrs) }];"


def render_label(title: str, inputs: list[str], outputs: list[str]) -> str:
    pieces = [escape_label(title)]
    pieces.extend(f"<{port}>{port}\\l" for port in inputs)
    pieces.extend(f"<{port}>{port}\\r" for port in outputs)
    return "|".join(pieces)


def escape_label(text: str) -> str:
    return text.replace("\\", "\\\\").replace('"', '\\"')


if __name__ == "__main__":
    raise SystemExit(main())
