// runtime/combine — see combine.h. 照 TiXL Combine.cs:16-265; forks named in the header.
#include "runtime/combine.h"

#include <algorithm>
#include <map>

namespace sw {
namespace {

bool inSelection(const std::vector<int>& ids, int childId) {
  return std::find(ids.begin(), ids.end(), childId) != ids.end();
}

// The selected children's bounding box (positions are node top-lefts; fine for centering).
void selectionBounds(const Symbol& parent, const std::vector<int>& ids, float& minX,
                     float& minY, float& maxX, float& maxY) {
  bool first = true;
  for (const SymbolChild& c : parent.children) {
    if (!inSelection(ids, c.id)) continue;
    if (first) { minX = maxX = c.x; minY = maxY = c.y; first = false; continue; }
    minX = std::min(minX, c.x); maxX = std::max(maxX, c.x);
    minY = std::min(minY, c.y); maxY = std::max(maxY, c.y);
  }
}

// A slot's def on the SYMBOL a child references (the lib carries atomics too — they are
// imported on AddChild / regenerated by the loader). nullptr when unresolvable.
const SlotDef* slotDefOf(const SymbolLibrary& lib, const Symbol& parent, int childId,
                         const std::string& slotId, bool isInput) {
  const SymbolChild* c = childById(parent, childId);
  const Symbol* s = c ? lib.find(c->symbolId) : nullptr;
  if (!s) return nullptr;
  const std::vector<SlotDef>& defs = isInput ? s->inputDefs : s->outputDefs;
  for (const SlotDef& d : defs)
    if (d.id == slotId) return &d;
  return nullptr;
}

// Unique slot id within the new symbol: the base name, then base1, base2, ... (TiXL's
// duplicate-name counter, Combine.cs:56-58).
std::string uniqueSlotId(const std::string& base, const std::vector<SlotDef>& ins,
                         const std::vector<SlotDef>& outs) {
  auto taken = [&](const std::string& id) {
    for (const SlotDef& d : ins)
      if (d.id == id) return true;
    for (const SlotDef& d : outs)
      if (d.id == id) return true;
    return false;
  };
  if (!taken(base)) return base;
  for (int n = 1;; ++n) {
    std::string cand = base + std::to_string(n);
    if (!taken(cand)) return cand;
  }
}

}  // namespace

CombineResult combineChildren(SymbolLibrary& lib, const std::string& parentSymbolId,
                              const std::vector<int>& childIds, const std::string& name) {
  CombineResult r;
  Symbol* parent = lib.find(parentSymbolId);
  if (!parent) { r.error = "parent symbol not found"; return r; }
  if (childIds.empty()) { r.error = "nothing selected"; return r; }
  for (int id : childIds)
    if (!childById(*parent, id)) { r.error = "selected child missing"; return r; }

  // Generated DEFINITION id: ASCII, unique, outside the "sw-type:"/uuid namespaces
  // (compound_save resolves compounds first, but staying out keeps reasoning trivial).
  std::string newId;
  for (int n = 1;; ++n) {
    newId = "Compound-" + std::to_string(n);
    if (!lib.symbols.count(newId)) break;
  }

  Symbol sym;
  sym.id = newId;
  sym.name = name.empty() ? newId : name;
  sym.atomic = false;

  // --- move children (ids regenerated 1..N; overrides verbatim; positions re-based so the
  // subgraph starts near the canvas origin area) ---
  float minX = 0, minY = 0, maxX = 0, maxY = 0;
  selectionBounds(*parent, childIds, minX, minY, maxX, maxY);
  std::map<int, int> oldToNew;
  for (const SymbolChild& c : parent->children) {  // parent order -> stable new numbering
    if (!inSelection(childIds, c.id)) continue;
    SymbolChild moved = c;
    moved.id = (int)oldToNew.size() + 1;
    moved.x = c.x - minX + 320.0f;  // children sit right of the input column below
    moved.y = c.y - minY + 160.0f;
    oldToNew[c.id] = moved.id;
    sym.children.push_back(moved);
  }
  sym.nextChildId = (int)oldToNew.size() + 1;

  // --- move the moved children's ANIMATOR curves into the new compound, then scrub them off the
  // parent (BROKEN-1 fix; = TiXL Combine.cs:170-190: CopyAnimationsTo into the new Symbol +
  // RemoveAnimationsFromInstances on the parent). Without this the new compound has no curves AND
  // the parent keeps殭屍 entries keyed on now-removed children (in-memory leak; a re-save scrubs
  // them via S15 but never self-heals in-memory). copyAnimationsTo remaps childId through oldToNew;
  // removeChild drops the parent's whole bucket per moved child. childIds is the moved set. ---
  parent->animator.copyAnimationsTo(sym.animator, childIds, oldToNew);
  for (int id : childIds) parent->animator.removeChild(id);

  // --- classify the parent's wires in ORDER (multi-input order contract) ---
  std::vector<SymbolConnection> internalWires, inbound, outbound, kept;
  for (const SymbolConnection& w : parent->connections) {
    const bool srcIn = w.srcChild != kSymbolBoundary && inSelection(childIds, w.srcChild);
    const bool dstIn = w.dstChild != kSymbolBoundary && inSelection(childIds, w.dstChild);
    if (srcIn && dstIn) internalWires.push_back(w);
    else if (dstIn) inbound.push_back(w);
    else if (srcIn) outbound.push_back(w);
    else kept.push_back(w);
  }

  // Boundary-def count cap (99): a deliberate, kept practical limit on how many external ports
  // one symbol may expose — mirrors TiXL and keeps the combined-index space tiny. (The editor's
  // boundary pin encoding now sits in its own high band, so this is no longer the old "index >= 100
  // aliases child 1's pins" arithmetic; the cap is a parity/sanity ceiling, not an encoding floor.)
  // Refuse BEFORE surgery, mirror of the compound_save load guard (refuter 批次4 #1).
  {
    std::map<std::pair<int, std::string>, bool> distinctOut;
    for (const SymbolConnection& w : outbound) distinctOut[{w.srcChild, w.srcSlot}] = true;
    if (inbound.size() + distinctOut.size() > 99) {
      r.error = "too many boundary crossings (max 99)";
      return r;
    }
  }

  for (const SymbolConnection& w : internalWires)
    sym.connections.push_back({oldToNew[w.srcChild], w.srcSlot, oldToNew[w.dstChild], w.dstSlot});

  // --- inbound crossings -> inputDefs + inner boundary wires + parent rewires ---
  std::vector<SymbolConnection> rewires;
  const int instanceId = nextFreeChildId(*parent);
  float inY = 160.0f;
  for (const SymbolConnection& w : inbound) {
    const SlotDef* d = slotDefOf(lib, *parent, w.dstChild, w.dstSlot, /*isInput=*/true);
    if (!d) continue;  // unresolvable target: drop the crossing (cook-tolerance spirit)
    SlotDef in;
    in.id = uniqueSlotId(w.dstSlot, sym.inputDefs, sym.outputDefs);
    in.name = in.id;
    in.dataType = d->dataType;
    in.def = d->def;  // FORK vs TiXL (type default): the slot's declared default
    in.x = 40.0f;
    in.y = inY; inY += 90.0f;
    sym.inputDefs.push_back(in);
    sym.connections.push_back({kSymbolBoundary, in.id, oldToNew[w.dstChild], w.dstSlot});
    rewires.push_back({w.srcChild, w.srcSlot, instanceId, in.id});
  }

  // --- outbound crossings -> ONE outputDef per distinct (srcChild, srcSlot) ---
  std::map<std::pair<int, std::string>, std::string> outFor;  // (src,slot) -> outputDef id
  float outX = (maxX - minX) + 600.0f, outY = 160.0f;
  for (const SymbolConnection& w : outbound) {
    auto key = std::make_pair(w.srcChild, w.srcSlot);
    auto it = outFor.find(key);
    if (it == outFor.end()) {
      const SlotDef* d = slotDefOf(lib, *parent, w.srcChild, w.srcSlot, /*isInput=*/false);
      if (!d) continue;
      SlotDef out;
      out.id = uniqueSlotId(w.srcSlot, sym.inputDefs, sym.outputDefs);
      out.name = out.id;
      out.dataType = d->dataType;
      out.x = outX;
      out.y = outY; outY += 90.0f;
      sym.outputDefs.push_back(out);
      sym.connections.push_back({oldToNew[w.srcChild], w.srcSlot, kSymbolBoundary, out.id});
      it = outFor.insert({key, out.id}).first;
    }
    rewires.push_back({instanceId, it->second, w.dstChild, w.dstSlot});
  }

  // --- parent surgery: drop the moved children + every wire that touched them, add the
  // ONE instance at the selection's center, then the rewires in original crossing order ---
  auto& cs = parent->children;
  cs.erase(std::remove_if(cs.begin(), cs.end(),
                          [&](const SymbolChild& c) { return inSelection(childIds, c.id); }),
           cs.end());
  parent->connections = std::move(kept);
  SymbolChild inst;
  inst.id = instanceId;
  inst.symbolId = newId;
  inst.x = (minX + maxX) * 0.5f;
  inst.y = (minY + maxY) * 0.5f;
  parent->children.push_back(inst);
  if (instanceId + 1 > parent->nextChildId) parent->nextChildId = instanceId + 1;
  for (const SymbolConnection& w : rewires) parent->connections.push_back(w);

  lib.symbols[newId] = sym;
  r.ok = true;
  r.newSymbolId = newId;
  r.newChildId = instanceId;
  return r;
}

}  // namespace sw
