#!/usr/bin/env python3
"""Convert recorded BespokeSynth control snapshots into an AUDIO_INGEST fixture.

Bespoke exposes named scalar controls per module ("module.control" -> value) over
its OSC bridge (see tools/bespoke_cli). A SemanticPath recording is a time series
of those control values; this tool diffs consecutive snapshots into the
AUDIO_INGEST_CONTRACT.md message log (`setValue` on change, `connect`/`disconnect`
on bridge availability), assigning a stable integer trackId per module.

    python3 tools/bespoke_to_ingest.py <snapshots.json> <out_fixture.json>

Input snapshot-log schema (what a live poller of `bespoke_cli` would emit):

    {
      "fps": 60,
      "snapshots": [
        { "t": 0.0, "connected": true, "controls": { "reverb.gain": 0.0, "filter.cutoff": 0.2 } },
        { "t": 0.5, "connected": true, "controls": { "reverb.gain": 0.8, "filter.cutoff": 0.2 } },
        { "t": 1.0, "connected": false, "controls": {} }
      ]
    }

Capturing snapshots live requires a running BespokeSynth + native OSC bridge; this
converter is the pure, host-independent transform and is unit-tested without one.
"""
import json
import sys
from pathlib import Path


def convert(snap_log):
    fps = int(snap_log.get("fps", 60))
    snaps = snap_log.get("snapshots", [])

    track_ids = {}  # module name -> stable int id (first-seen order)

    def track_id(module):
        if module not in track_ids:
            track_ids[module] = len(track_ids)
        return track_ids[module]

    messages = []
    prev_connected = None
    prev_values = {}  # "module.control" -> last emitted value

    for snap in snaps:
        t = float(snap["t"])
        connected = bool(snap.get("connected", True))

        if prev_connected is None:
            if connected:
                messages.append({"t": t, "kind": "connect", "track": 0})
        elif connected != prev_connected:
            messages.append({"t": t, "kind": "connect" if connected else "disconnect", "track": 0})
        prev_connected = connected

        controls = snap.get("controls") or {}
        for key in sorted(controls):  # sorted -> deterministic message + trackId order
            val = float(controls[key])
            if key in prev_values and prev_values[key] == val:
                continue  # diff: only changed/new controls become setValue (latest-wins is the engine's job)
            prev_values[key] = val
            module, control = key.split(".", 1) if "." in key else (key, "value")
            messages.append(
                {"t": t, "kind": "setValue", "track": track_id(module), "param": control, "value": val}
            )

    max_t = max((float(s["t"]) for s in snaps), default=0.0)
    frames = int(round(max_t * fps)) + 2
    track_map = {str(tid): module for module, tid in track_ids.items()}

    return {
        "version": "0.1",
        "graphId": "fixture.audio_ingest_bespoke",
        "note": "Generated by tools/bespoke_to_ingest.py from recorded BespokeSynth control snapshots.",
        "frameClock": {"fps": fps, "frames": frames},
        "ingest": {"policy": "hold", "smoothing": 0.6},
        "trackMap": track_map,
        "messages": messages,
    }


def main(argv):
    if len(argv) < 3:
        print("usage: bespoke_to_ingest.py <snapshots.json> <out_fixture.json>", file=sys.stderr)
        return 2
    snap_log = json.loads(Path(argv[1]).read_text(encoding="utf-8"))
    fixture = convert(snap_log)
    Path(argv[2]).write_text(json.dumps(fixture, indent=2) + "\n", encoding="utf-8")
    print(
        f"[bespoke->ingest] {len(fixture['messages'])} messages, "
        f"{len(fixture['trackMap'])} tracks -> {argv[2]}"
    )
    return 0


if __name__ == "__main__":
    raise SystemExit(main(sys.argv))
